version: "3.7"

services:
  spark-master:
    # image: bitnami/spark:3.3.3
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
      - "8050:8050"
    networks:
      - app
  spark-worker-1:
    # image: bitnami/spark:3.3.3
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - app
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    # image: bitnami/spark:3.3.3
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - app
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  mongo:
    image: "mongo:jammy"
    ports:
      - 27017:27017
    networks:
      - app
    volumes:
      - db_data:opt/bitnami/data/db
volumes:
  db_data:
networks:
  app: