version: "3.7"

services:
  mongo:
    image: "mongo:jammy"
    ports:
      - "27027:27017"
    networks:
      - app
    volumes:
      - ./db_data/_data:/data/db
  spark-master:
#    image: myapp
    build: .
    entrypoint: /init.sh
    ports:
      - "9090:8080"
      - "7077:7077"
      - "8050:8050"
    depends_on:
      - mongo
    networks:
      - app
  spark-worker-1:
#    image: myapp
    build: .
    command: ../bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - app
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
#    image: myapp
    build: .
    command: ../bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - app
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
networks:
  app: