services:
  # dash-app:
  #   build: .
  #   ports:
  #     - "8050:8050"
  #   networks:
  #     - app
  #   depends_on:
  #     - spark-master
  spark-master:
    image: bitnami/spark:3.3.3
    # build: 
    #   context: .
    #   dockerfile: spark.dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports: 
      - "9090:8080"
      - "7077:7077"
    networks:
      - app
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_LOGS_ENABLE=yes
      - SPARK_WORKER_LOGS_ENABLE=yes
  spark-worker-1:
    image: bitnami/spark:3.3.3
    # build: 
    #   context: .
    #   dockerfile: spark.dockerfile
    # hostname: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WOKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - app
  mongo:
    image: "mongo:jammy"
    ports:
      - 27037:27017
    networks:
      - app
    volumes:
      - db_data:/data/db

volumes:
  db_data:
networks:
  app:
 